@startuml Checker Sequence Diagram
participant UserInterface
participant "missing_implicit:rule.MissingImplicit" as MissingImplicit
participant "my_style:rule.LFRicStyle" as LFRicStyle
participant engine.CheckEngine as CheckEngine
participant source.SourceFactory
participant "some_text:source.SourceFileReader" as SourceFileReader
participant "source_tree:source.FortranSource" as FortranSource

UserInterface -\ MissingImplicit : <<create>>
activate MissingImplicit

UserInterface -\ LFRicStyle : LFRicStyle(mising_implicit) <<create>>
activate LFRicStyle

UserInterface -\ CheckEngine : CheckEngine(my_style) <<create>>
activate CheckEngine

UserInterface -> source.SourceFactory: read_file(filename)

source.SourceFactory -\ SourceFileReader: SourceFileReader(filename) <<create>>
activate SourceFileReader

source.SourceFactory -\ FortranSource: FortranSource(some_text) <<create>>
activate FortranSource

source.SourceFactory --> UserInterface: source_tree

UserInterface -> CheckEngine : check(source_tree)

CheckEngine -> FortranSource : get_tree()
FortranSource --> CheckEngine : root:Program

CheckEngine -> LFRicStyle : check(root)
LFRicStyle -> MissingImplicit : examine(root)
MissingImplicit --> LFRicStyle : Issues[]
LFRicStyle --> CheckEngine : Issues[]

CheckEngine --> UserInterface : Issues[]

@enduml
