[build-system]
requires = ['setuptools']
build-backend = 'setuptools.build_meta'

[project]
name='stylist'
description="Flexible source code style checking tool"
requires-python = '>=3.9'
license = {text = 'BSD 3-Clause License'}
dependencies = ['fparser >= 0.1.2']
dynamic = ['version', 'readme']
keywords = ['linter', 'fortran']
classifiers = [
    'Development Status :: 3 - Alpha',
    'Intended Audience :: Developers',
    'Topic :: Software Development :: Quality Assurance',
    'License :: OSI Approved :: BSD License',
    'Programming Language :: Python :: 3'
]


[project.optional-dependencies]
dev = ['check-manifest', 'flake8']
test = ['pytest', 'pytest-cov', 'mypy']
performance = ['pytest', 'pytest-benchmark', 'matplotlib']
docs = ['sphinx < 7.0.0',
        'sphinx-autodoc-typehints',
        'sphinxcontrib-plantuml>=0.30.0',
        'pillow>=11.0.0',
        'pydata-sphinx-theme>=0.15.2',
        'sphinxcontrib.plantuml']
release = ['setuptools', 'wheel', 'twine']

[project.scripts]
stylist = 'stylist.__main__:main'

[project.urls]
homepage = 'https://github.com/MetOffice/stylist/'
documentation = 'https://metoffice.github.io/stylist'
'Bug Reports' = 'https://github.com/MetOffice/stylist/issues'
repository = 'https://github.com/MetOffice/stylist/'

[tool.setuptools.dynamic]
readme = {file = 'README.rst'}
version = {attr = 'stylist.__version__'}

[tool.setuptools.packages.find]
where = ['source']
